conftype: configuration
title: "小程序登录文档配置"
pluginident: "wxapp_login_docs" #插件标识
status: true
data:
  user_agreement_title: "用户协议"  #用户协议标题
  user_agreement_content: "<h3 id=\"gg4hup\" data-toc-id=\"gg4hup\">用户协议</h3><p>请在此处维护用户协议富文本内容。</p><p></p><p></p><p>3</p><p></p><p>3</p><p>3</p><p>3</p><p></p>"  #用户协议富文本（HTML）
  user_agreement_url: ""  #用户协议链接（建议 https）
  privacy_policy_title: "隐私政策"  #隐私政策标题
  privacy_policy_content: "<h3 id=\"gpgo1c\" data-toc-id=\"gpgo1c\">隐私政策</h3><p>请在此处维护隐私政策富文本内容。</p><p>2</p><p>2</p><p>22</p><p>2</p><p></p>"  #隐私政策富文本（HTML）
  privacy_policy_url: ""  #隐私政策链接（建议 https）
  help_center_title: "帮助中心"  #帮助中心标题
  help_center_content: "<h3 id=\"kqfw3z\" data-toc-id=\"kqfw3z\">帮助中心</h3><p>请在此处维护帮助中心富文本内容。</p><p>1</p><p>11</p><p>1</p><p></p><p></p>"  #帮助中心富文本（HTML）
  help_center_url: ""  #帮助中心链接（建议 https）
